version: "2.1"
services:
  invoicebase:
    extends:
      file: docker-compose.base.yml
      service: base
    build:
      args:
        INSTALL_GROUPS: development
    networks:
      - invoicebase
    volumes:
      - invoicebase_files:/invoicebase:nocopy
    ports:
      - "3001:3000"
    links:
      - database:db

  database:
    extends:
      file: docker-compose.base.yml
      service: database

networks:
  invoicebase:
volumes:
  db-data:
  invoicebase_files:
    external: true
